# Generated by Django 2.1.14 on 2021-05-25 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insuree', '0004_confirmationtype_education_profession_relation'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsureeVerify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=300)),
                ('password', models.CharField(max_length=50)),
                ('insuree', models.OneToOneField(blank=True, db_column='InsureeID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='verified_insurees', to='insuree.Insuree')),
            ],
        ),
    ]
