# Generated by Django 2.1.14 on 2021-05-26 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0004_confirmationtype_education_profession_relation'),
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InsureeVerify',
            new_name='InsureeAuth',
        ),
    ]
