# Generated by Django 2.1.14 on 2021-06-03 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0004_confirmationtype_education_profession_relation'),
        ('webapp', '0006_healthfacilitycoordinate'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher', models.FileField(upload_to='insuree_voucher')),
                ('is_entry', models.BooleanField(default=False)),
                ('insuree', models.ForeignKey(blank=True, db_column='InsureeID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='voucher_payment_insurees', to='insuree.Insuree')),
            ],
        ),
    ]
