# Generated by Django 2.1.14 on 2021-06-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_voucherpayment_vocher_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucherpayment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date added'),
        ),
        migrations.AddField(
            model_name='voucherpayment',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date updated'),
        ),
        migrations.AlterField(
            model_name='voucherpayment',
            name='vocher_id',
            field=models.CharField(default='20210615141346', max_length=50),
        ),
    ]
