# Generated by Django 2.1.14 on 2021-06-17 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_voucherpayment_vocher_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('mobile_number', models.CharField(max_length=15)),
                ('email_address', models.EmailField(max_length=50)),
                ('queries', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='voucherpayment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date added'),
        ),
        migrations.AddField(
            model_name='voucherpayment',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date updated'),
        ),
        migrations.AlterField(
            model_name='voucherpayment',
            name='vocher_id',
            field=models.CharField(default='20210617221748', max_length=50),
        ),
    ]
