# Generated by Django 2.1.14 on 2021-06-23 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_auto_20210623_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucherpayment',
            name='vocher_id',
            field=models.CharField(default='20210623080942', max_length=50),
        ),
    ]
