# Generated by Django 2.1.14 on 2021-06-23 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_auto_20210623_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='chf_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='voucherpayment',
            name='vocher_id',
            field=models.CharField(default='20210623213119', max_length=50),
        ),
    ]
