# Generated by Django 2.1.14 on 2021-07-04 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_auto_20210627_0808'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsureeTempReg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json', models.TextField()),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='voucherpayment',
            name='vocher_id',
            field=models.CharField(default='20210704224936', max_length=50),
        ),
    ]
