# Generated by Django 2.1.14 on 2021-07-07 23:10

import core.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_auto_20210704_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsureePic',
            fields=[
                ('id', models.AutoField(db_column='PhotoID', primary_key=True, serialize=False)),
                ('uuid', models.CharField(db_column='PhotoUUID', default=uuid.uuid4, max_length=36, unique=True)),
                ('chf_id', models.CharField(blank=True, db_column='CHFID', max_length=12, null=True)),
                ('folder', models.CharField(blank=True, db_column='PhotoFolder', max_length=255, null=True)),
                ('filename', models.CharField(blank=True, db_column='PhotoFileName', max_length=250, null=True)),
                ('photo', models.TextField(blank=True, null=True)),
                ('officer_id', models.IntegerField(db_column='OfficerID')),
                ('date', core.fields.DateField(db_column='PhotoDate')),
                ('audit_user_id', models.IntegerField(blank=True, db_column='AuditUserID', null=True)),
            ],
            options={
                'db_table': 'tblPhotos',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='insureetempreg',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date added'),
        ),
        migrations.AddField(
            model_name='insureetempreg',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date added'),
        ),
        migrations.AlterField(
            model_name='voucherpayment',
            name='vocher_id',
            field=models.CharField(default='20210707231020', max_length=50),
        ),
    ]
