# Generated by Django 2.1.14 on 2021-05-30 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='insuree',
        ),
        migrations.AddField(
            model_name='insureeauth',
            name='otp',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
