# Generated by Django 2.1.14 on 2021-06-23 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0004_confirmationtype_education_profession_relation'),
        ('webapp', '0011_auto_20210623_0809'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date added')),
                ('insuree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insuree_nofification', to='insuree.Insuree')),
            ],
        ),
        migrations.AddField(
            model_name='feedback',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date added'),
        ),
        migrations.AlterField(
            model_name='voucherpayment',
            name='vocher_id',
            field=models.CharField(default='20210623201635', max_length=50),
        ),
    ]
