# Generated by Django 2.1.14 on 2021-07-10 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_auto_20210707_2310'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChfidTempInsuree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chfid', models.CharField(max_length=100)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date added')),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date added')),
            ],
        ),
        migrations.AlterField(
            model_name='voucherpayment',
            name='vocher_id',
            field=models.CharField(default='20210710125538', max_length=50),
        ),
    ]
