# Generated by Django 2.1.14 on 2021-07-15 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0019_auto_20210715_0721'),
    ]

    operations = [
        migrations.AddField(
            model_name='insureetempreg',
            name='is_hold',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='insureetempreg',
            name='is_rejected',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='insureetempreg',
            name='status_message',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='insureetempreg',
            name='is_approved',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='voucherpayment',
            name='vocher_id',
            field=models.CharField(default='20210715073208', max_length=50),
        ),
    ]
